document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\"UTF-8\">");
document.writeln("<title>Your Page</title>");
document.writeln("<style>");
document.writeln("#fubiaoo {");
document.writeln("z-index:2;");
document.writeln("display: none; /* 首先隐藏元素 */");
document.writeln("text-align: center;");
document.writeln("width: 150px;");
document.writeln("height: 0px;");
document.writeln("position: fixed;");
document.writeln("right: -35px;");
document.writeln("bottom: 330px;");
document.writeln("left: auto;");
document.writeln("border-radius: 50%;");
document.writeln("}");
document.writeln("");
document.writeln("#close-button {");
document.writeln("clear: both;");
document.writeln("text-align: center; ");
document.writeln("border-radius: 5px; ");
document.writeln("background: rgba(0,0,0,.7); ");
document.writeln("color: #fff; ");
document.writeln("padding: 3px 6px; ");
document.writeln("font-weight: normal; ");
document.writeln("line-height: 20px; ");
document.writeln("z-index: 999;");
document.writeln("}");
document.writeln("");
document.writeln("/* 当鼠标悬浮在关闭按钮上时，按钮放大 */");
document.writeln("#close-button:hover {");
document.writeln("cursor: pointer;");
document.writeln("transform: scale(1.1);");
document.writeln("transition: transform 0.5s;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div id=\"fubiaoo\">");
document.writeln("<a target=\"_blank\" href=\"https://yadg.13-10594.shop\"><img src=\"https://fbhbrgbrg.3366444.com/images/liuhe.gif\" width=\"50%\" margin-top=\"285px\" /></a>");
document.writeln("<a target=\"_blank\" href=\"https://yadg.13-10594.shop\"><img src=\"https://fbhbrgbrg.3366444.com/images/dianjizhuce.png\" width=\"50%\" margin-top=\"285px\" /></a>");
document.writeln("<a target=\"_blank\" href=\"https://yadg.13-10594.shop\"><img src=\"https://fbhbrgbrg.3366444.com/images/chengxinwangtou.gif\" width=\"50%\" margin-top=\"405px\" /></a></br>");
document.writeln("<span id=\"close-button\" onclick=\"hideElement()\">关闭 x </span> ");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("/* 设置隐藏元素的时间（单位：毫秒） */");
document.writeln("var hideTimeoutInMilliseconds = 60 * 1000; // 设置为1分钟，因为1分钟等于60,000毫秒");
document.writeln("");
document.writeln("var hideTimeoutInMilliseconds = 5 * 1000; // 如果想设置为1秒，请取消注释这一行，因为1秒等于1,000毫秒");
document.writeln("");
document.writeln("/* 隐藏元素的函数 */");
document.writeln("function hideElement() {");
document.writeln("var element = document.getElementById(\"fubiaoo\");");
document.writeln("element.style.display = \'none\';");
document.writeln("");
document.writeln("var hideUntil = new Date();");
document.writeln("hideUntil.setTime(hideUntil.getTime() + hideTimeoutInMilliseconds);");
document.writeln("if(window.localStorage) {");
document.writeln("localStorage.setItem(\'hideUntil\', hideUntil);");
document.writeln("}");
document.writeln("}");
document.writeln("");
document.writeln("/* 网页加载完成后，检查元素是否应该被隐藏 */");
document.writeln("window.onload = function() {");
document.writeln("if(window.localStorage) {");
document.writeln("var hideUntil = new Date(localStorage.getItem(\'hideUntil\'));");
document.writeln("if (hideUntil && hideUntil > new Date()) {");
document.writeln("var element = document.getElementById(\"fubiaoo\");");
document.writeln("element.style.display = \'none\';");
document.writeln("} else {");
document.writeln("var element = document.getElementById(\"fubiaoo\");");
document.writeln("element.style.display = \'block\'; /* 如果元素应该被显示，就显示它 */");
document.writeln("}");
document.writeln("}");
document.writeln("}");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");